language: go
go:
- '1.12'
env:
- PATH=/home/travis/gopath/bin:$PATH GO111MODULE=on
script: go test
before_deploy:
- go get -v github.com/mitchellh/gox
- gox -output build/{{.OS}}_{{.Arch}}/{{.Dir}}
- cd build
- for osarch in * ; do cd $osarch && zip -r ../metrin-$osarch.zip . && cd ../ ; done
- cd ../
deploy:
  provider: releases
  api_key:
    secure: CzPitqnFnltxB/+RJHT32Q0A/9l6W679srvD7b1FAjl2o9hKThYzhMN6k/64vneVOUqHvj13KwstAL+CmFqlQMrfabgUd+gSzI1wdvF1WguPEhvM7inDLtgYP0i+aqQHgnWKaoPDPG00EwJlCTdEz1UvsBefixEMopeq8Xp+WL6m5519jQOawg2TyPpCYOlbcma9lh+FaZO3dpSitoZWkIJ5umKOI3fSGwb1gR/ermGk9r25Qfkd7E/dc+lcuuD83WEGfInh3NLL5o6tf03iUDjq4LhBUYi26yg5c/Q3vTd2UAzceA/vINrBobUjBa9mmhaajRHfrJg0W36bAJkXFrkyo5cIXHtimW1lts8BFUYIg5Av6oiSAD1Ff5b9Gt4oou8dq4rwVRjO7Dr7YCJqC/BbkxhQU2JpewLmRgCq2qjs9P3pQ6HWqC5nYk1wwLh3oaXxka9Z4gPy1Ig4pFVJwpof/krT0Qypp1sXq7STnm2YLrKu5zPILAXISTYzqhKX84kcXZo+0zJ6wsQ38FaMVHMhsYN71QgF2DgJtsU+nM4ntgMsSAWpj0dZGvo0v+nCLU71tgul2KRSA/3YQ1MaS0emVvUk00Mv3x2mYs/0+RjRe45yEpT/yqvhyzNORgODYxdAnXhBE+oXa2TSH6KpofMqdIvWQSFK6idg0BthW/0=
  file:
  - build/metrin-darwin_386.zip
  - build/metrin-darwin_amd64.zip
  - build/metrin-freebsd_386.zip
  - build/metrin-freebsd_amd64.zip
  - build/metrin-freebsd_arm.zip
  - build/metrin-linux_386.zip
  - build/metrin-linux_amd64.zip
  - build/metrin-linux_arm.zip
  - build/metrin-netbsd_386.zip
  - build/metrin-netbsd_amd64.zip
  - build/metrin-netbsd_arm.zip
  - build/metrin-openbsd_386.zip
  - build/metrin-openbsd_amd64.zip
  - build/metrin-windows_386.zip
  - build/metrin-windows_amd64.zip
  skip_cleanup: true
  all_branches: true
  on:
    repo: y13i/metrin
    tags: true
